carrito/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.carro, name='cart'),
    path('agregar_carro/<int:producto_id>/', views.agregar_carro, name='agregar_carro'),
    path('eliminar_carro/<int:producto_id>/', views.eliminar_carro, name='eliminar_carro'),
    path('eliminar_carro_item/<int:producto_id>/', views.eliminar_carro_item, name='eliminar_carro_item'),
]

ecommerce/urls.py
from . import views
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static  import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home , name="home"),
    path('productos/',include('productos.urls')),
    path('carro/',include('carrito.urls'))

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.productos, name="productos"),
    path('categoria/<slug:categoria_slug>/',views.productos,name='productos_de_categoria'),# path dinamico
    path('categoria/<slug:categoria_slug>/<slug:producto_slug>/',views.productos_detalle, name='productos_detalle'),
    path('buscar/', views.buscar, name='buscar'),
]

productos/models.py
from django.urls import reverse
from django.db import models
from categoria.models import Categoria

# Create your models here.
class Producto(models.Model):
    nombre_producto= models.CharField(max_length=200,unique=True)
    slug = models.CharField(max_length=200,unique=True)
    descripcion=models.CharField(max_length=500,blank=True)
    precio= models.IntegerField()
    imagen= models.ImageField(upload_to='photos/productos')
    stock=models.IntegerField()
    valido=models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE) # se invoca  como si clave  foranea y si se borra  la categoria  se borra los productos relacionados 
    fecha_creacion=models.DateTimeField(auto_now_add=True)
    fecha_modificacion=models.DateField(auto_now=True)

    def get_url(self):
        #  se llama  el get url  desde  lo ulrs esto quiere decir que nesesitamos 2 parametros  como se ven en el 
        #path de ulrsse nesesita el slug de categoria  y producto
        return reverse('productos_detalle', args=[self.categoria.slug, self.slug])

    def __str__(self):
        return  self.nombre_producto


# para filtar  el color y talla
class VariacionManager(models.Manager):
      
      def colors(self):
          return super(VariacionManager, self).filter(variacion_categoria='color', valido=True)
       
      def tallas(self):
          return super(VariacionManager, self).filter(variacion_categoria='talla', valido=True)

variacion_categoria_choice=(
  ('color','color'),
  ('talla','talla'),

)

# sirve  para hacer variaciones  como color  o talla
class Variacion(models.Model):
    
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    variacion_categoria= models.CharField(max_length=100, choices=variacion_categoria_choice)
    variacion_value= models.CharField(max_length=100)
    valido=models.BooleanField(default=True)
    fecha_creacion= models.DateTimeField(auto_now=True)
    
    objects= VariacionManager()

    def __str__(self) :
        return self.variacion_categoria + ':' + self.variacion_value

productos/views.py
from django.shortcuts import get_object_or_404, render
from carrito.models import CarroItem
from .models import Producto
from categoria.models import Categoria
from carrito.models import CarroItem
from carrito.views import _carro_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q 
# Create your views here.

def productos(request, categoria_slug=None):
    categorias = None
    productos= None

    if categoria_slug != None :
        categorias = get_object_or_404(Categoria, slug=categoria_slug)# si en cuentra la categoria   le enlista  y si no la encuentra mandara  un error 404
        productos = Producto.objects.filter(categoria=categorias,valido=True).order_by('id')
        paginator =Paginator(productos,10)
        page= request.GET.get('page')
        paged_productos=paginator.get_page(page)
        producto_cantidad= productos.count()
    else:
      productos=  Producto.objects.all().filter(valido=True).order_by('id')
      #aqui indicamos cuantos elementos queremos adentor de  la pagina
      paginator =Paginator(productos,10)
      page= request.GET.get('page')
      paged_productos=paginator.get_page(page)
      #-------
      producto_cantidad= productos.count()
    
    
    context={
        'productos':paged_productos,
        'producto_cantidad':producto_cantidad,
    }
    return render(request, 'productos/productos.html',context)

def productos_detalle(request,categoria_slug,producto_slug):

#se busca por el slug la categoria  y el producto por el slug
    try:
        single_producto = Producto.objects.get(categoria__slug=categoria_slug, slug=producto_slug)
        in_cart =CarroItem.objects.filter(cart__carro_id=_carro_id(request), producto=single_producto).exists()
    except Exception as e:
           raise e
    #si se encuentra el producto en la base de datos se  guarda en un dicionario y lo mandamos
    #por el render
    context={
        'single_producto': single_producto,
        'in_cart':in_cart,
    }

    return render(request,'productos/producto_detalles.html', context)


def buscar(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
    if keyword:
        productos= Producto.objects.order_by('-fecha_creacion').filter(Q(descripcion__icontains=keyword) | Q(nombre_producto=keyword)) 
        productos_count=productos.count()
        context={
            'productos':productos,
            'productos_count':productos_count,
        } 
    return render(request,'productos/productos.html',context)

templates/productos/carro.html
{% extends 'base.html'%}

{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not carro_items %}
     <h2 class="text-center"> El carrito de compras esta vacio</h2>
     <br>
     <div class="text-center">
         <a href="{% url 'productos' %}" class="btn btn-primary">Continua comprando</a>
     </div>
    {% else %}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Cantidad</th>
      <th scope="col" width="120">Precio</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>

    {% for carro_item in carro_items %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{ carro_item.producto.imagen.url}}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="{{ carro_item.producto.get_url }}" class="title text-dark">{{carro_item.producto.nombre_producto}}</a>
                    <p class="text-muted small">
                       {% if carro_item.variaciones.all %}
                          {% for item in carro_item.variaciones.all %}
                           
                            {{ item.variacion_categoria | capfirst }} : {{ item.variacion_value | capfirst }}

                           {% endfor %}
                       {% endif %}
                    </p>
                </figcaption>
            </figure>
        </td> 
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'eliminar_carro' carro_item.producto.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{ carro_item.cantidad }}">
                                <div class="input-group-append">
                                <a href="{% url 'agregar_carro' carro_item.producto.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">${{carro_item.sub_total}}</var> 
                <small class="text-muted"> ${{carro_item.producto.precio}} </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'eliminar_carro_item' carro_item.producto.id %}" class="btn btn-danger"> Eliminar</a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Precio:</dt>
                  <dd class="text-right">${{ total }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Impuesto:</dt>
                  <dd class="text-right"> ${{ inpuesto }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png'%}" height="26">
                </p>
                <a href="./place-order.html" class="btn btn-primary btn-block"> Pagar </a>
                <a href="{% url 'productos'%}" class="btn btn-light btn-block">Continua comprando</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    {% endif %}
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/productos/producto_detalles.html
{% extends 'base.html' %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 

        <div class="img-big-wrap">
            
           <a href="#"><img src="{{ single_producto.imagen.url }}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">


            
    <form action="{% url 'agregar_carro' single_producto.id %}" method="POST">
       <!-- para ser posibles que los valores del formulario puedan ser capturados  del servidor de  django-->
        {% csrf_token %}
      <article class="content-body">



    
    <h2 class="title">{{ single_producto.nombre_producto }}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">$ {{single_producto.precio }}</var> 
    </div> 
    
    <p>{{ single_producto.descripcion }}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Selecionar el Color</h6>
                <select name="color" class="form-control" required>
                <option value="" disabled selected>seleccione</option>
                {% for i in single_producto.variacion_set.colors %}
                <option value="{{ i.variacion_value | lower }}">{{ i.variacion_value | capfirst }}</option>
                {% endfor %}
                </select>
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Selecione la Talla</h6>
                <select name="talla" class="form-control" required>
                  <option value="" disabled selected>seleccione</option>
                  {% for i in single_producto.variacion_set.tallas %}
                  <option value="{{ i.variacion_value | lower }}">{{ i.variacion_value | capfirst }}</option>
                  {% endfor %}
                  </select>
            </div>
        </div> <!-- row.// -->
        <hr>
       
        {% if single_producto.stock <= 0 %}
          <h5>Producto fuera de stock</h5>
        {% else %}

             {% if in_cart %} 
             
             <a href="#" class="btn  btn-success"> <span class="text">Producto agregado al carro</span> <i class="fas fa-check"></i>  </a>
             <a href="{% url 'cart'%}" class="btn  btn-outline-primary"> <span class="text">ver carro</span> <i class="fas fa-eye"></i>  </a>
             {%else %}
             <button type="submit"  class="btn  btn-primary"> <span class="text">Agregar al shopping cart</span> <i class="fas fa-shopping-cart"></i>  </button>
            {% endif %}


        
        {% endif %}
        </article> <!-- product-info-aside .// -->
       </form>






            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/productos/productos.html
{% extends 'base.html'%}


{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Nuestra Tienda</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    <!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categorias</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    <li><a href="{% url 'productos' %}">Todo </a></li>
                    {% for categoria in links %}
                    <li><a href="{{ categoria.get_url }}">{{ categoria.nombre_categoria}}  </a></li>
                    {% endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Tamanos </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Precios </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Buscar</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"> <b>{{ producto_cantidad}} </b> Productos Encontrados </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        <!-- productos -->

        {%if productos %}
        {% for producto  in productos %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    
                   <a href="{{ producto.get_url }}"> <img src="{{ producto.imagen.url }}"> </a>
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{ producto.get_url }}" class="title">{{ producto.nombre_producto}}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">${{producto.precio}}.000</span>
                            
                        </div> <!-- price-wrap.// -->
                    </div>
                    <a href="{%  url 'agregar_carro' producto.id%}" class="btn btn-block btn-success">Agregar al carrito </a>
                </figcaption>
            </figure>
        </div> <!-- col.// -->
        {% endfor %}
        {% else %}
        <div>
            <h2>No se encontraron resultados.</h2>
        </div>
        {% endif %}
    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
        {% if productos.has_other_pages %}
      <ul class="pagination">
         {% if productos.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{productos.previous_page_number}}">Anterior</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Anterior</a></li>
        {% endif %}


        {% for i in productos.paginator.page_range %}
           {% if  productos.number == i   %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a></li>
           {% endif %}
        {% endfor %}
        {% if productos.has_next %}
        <li class="page-item active"><a class="page-link" href="?page={{productos.next_page_numbre}}">Siguiente</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Siguiente</a></li>
        
        {% endif %}
    </ul>
      {% endif %}
    </nav>
    
        </main> <!-- col.// -->

{% endblock  %}